config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("portfolio.pages.urls")),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("portfolio.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

portfolio/pages/urls.py
from django.urls import path

from portfolio.pages.views import HomeView, AboutView, ContactUsView, ProjectsView, ProjectView, SkillsView

urlpatterns = [
    path('home/', HomeView.as_view()),
    path('', HomeView.as_view(), name='home'),
    path('about-us/', AboutView.as_view(), name='about'),
    path('projects/', ProjectsView.as_view(), name='projects'),
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
    path('projects/<slug:slug>/', ProjectView.as_view(), name='project'),
    path('skills/', SkillsView.as_view(), name='skills'),
]

portfolio/users/urls.py
from django.urls import path

from portfolio.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

portfolio/pages/models.py
import datetime

from ckeditor.fields import RichTextField
from django.core import validators
from django.db import models
from django.db.models import CASCADE


class SiteSettings(models.Model):
    domain = models.CharField(max_length=300)
    name = models.CharField(max_length=255)
    job_title = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.domain} | {self.name}"


class Page(models.Model):
    title = models.CharField(max_length=200)
    icon = models.FileField(upload_to="icons/")
    slug = models.SlugField(max_length=300, unique=True)
    parent = models.ForeignKey("Page", on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    is_parent = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class About(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, null=True, blank=True)
    heading = models.CharField(max_length=200)
    body = RichTextField()

    def __str__(self):
        return self.heading


class SkillCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Skill(models.Model):
    category = models.ForeignKey(SkillCategory, on_delete=CASCADE)
    name = models.CharField(max_length=100)
    thumbnail = models.ImageField(blank=True, null=True)
    thumbnail_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{self.name} ({self.category})"


class ContactUs(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(validators=[validators.validate_email])
    message = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"From: {self.email} | Time: {self.created_on}"


class Project(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=300)
    star_count = models.IntegerField()
    fork_count = models.IntegerField()
    short_description = models.CharField(max_length=200)
    description = RichTextField()

    def __str__(self):
        return self.name


class SocialMedia(models.Model):
    name = models.CharField(max_length=100)
    link = models.URLField(max_length=300)
    icon = models.FileField(upload_to='icons/')

    def __str__(self):
        return self.name


class Education(models.Model):
    Degree = models.CharField(max_length=300)
    School = models.CharField(max_length=300)
    country = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    present = models.BooleanField(default=False)
    description = RichTextField()

    def __str__(self):
        return f"{self.Degree} | {self.School}"

portfolio/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for portfolio.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

portfolio/pages/forms.py
from django import forms

from portfolio.pages.models import ContactUs


class ContactUsModelForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['first_name', 'last_name', 'email', 'message']
        widgets = {
            "first_name": forms.TextInput(
                attrs={
                    "placeholder": "First Name"
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "placeholder": "Last Name"
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "placeholder": "Email"
                }
            ),
            "message": forms.Textarea(
                attrs={
                    "placeholder": "Your Message"
                }
            )
        }

portfolio/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

portfolio/pages/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

from portfolio.pages.forms import ContactUsModelForm
from portfolio.pages.models import SiteSettings, Page, About, ContactUs, Project, SkillCategory, SocialMedia


class HomeView(View):
    def get(self, request):
        if request.path == "/home/":
            return redirect(reverse('home'))
        home = Page.objects.get(slug="home")
        portfolio = SiteSettings.objects.first()
        context = {
            "page": home,
            "portfolio": portfolio
        }
        return render(request, "pages/index.html", context=context)


class AboutView(View):
    def get(self, request):
        about_us = Page.objects.get(slug="about-us")
        about = About.objects.first()
        context = {
            "page": about_us,
            "about": about
        }
        return render(request, "pages/about.html", context=context)


class ContactUsView(View):
    def get(self, request):
        contact_us_form = ContactUsModelForm()
        contact_us = Page.objects.get(slug="contact-us")
        context = {
            "contact_us_form": contact_us_form,
            "page": contact_us
        }
        return render(request, "pages/contact.html", context=context)

    def post(self, request):
        contact_us_form = ContactUsModelForm(request.POST)
        contact_us = Page.objects.get(slug="contact-us")
        context = {
            "contact_us_form": contact_us_form,
            "page": contact_us
        }
        if contact_us_form.is_valid():
            contact_us_form.save()
            messages.success(request, 'Message sent successfully', extra_tags='fa-sharp fa-solid fa-square-check fa-xl')
            return render(request, "pages/contact.html", context=context)
        return render(request, "pages/contact.html", context=context)


class ProjectsView(View):
    def get(self, request):
        page = Page.objects.get(slug="projects")
        projects = Project.objects.all().order_by("-star_count")
        context = {
            "page": page,
            "projects": projects
        }
        return render(request, "pages/projects.html", context=context)


class ProjectView(View):
    def get(self, request, slug):
        try:
            project = Project.objects.get(slug=slug)
            page = project.page
            context = {
                "page": page,
                "project": project
            }
            return render(request, "pages/project.html", context=context)
        except ObjectDoesNotExist:
            return render(request, "404.html")


class SkillsView(View):
    def get(self, request):
        page = Page.objects.get(slug="skills")
        skill_category = SkillCategory.objects.all()
        context = {
            "page": page,
            "skill_category": skill_category
        }
        return render(request, "pages/skills.html", context=context)


class SideBarView(TemplateView):
    template_name = "shared/sidebar.html"
    ordering = ['is_parent']

    def get_context_data(self, **kwargs):
        pages = Page.objects.all().order_by("-is_parent", "title")
        kwargs['pages'] = pages
        return super(SideBarView, self).get_context_data(**kwargs)


def render_navbar_title(request):
    portfolio = SiteSettings.objects.first()
    context = {
        "portfolio": portfolio
    }
    return render(request, "shared/partials/navbar_title.html", context=context)


def breadcrumb_title(request):
    portfolio = SiteSettings.objects.first()
    context = {
        "portfolio": portfolio
    }
    return render(request, "shared/partials/breadcrumb_title.html", context=context)


def render_social_media(request):
    social_medias = SocialMedia.objects.all()
    context = {
        'social_medias': social_medias
    }
    return render(request, 'shared/social_media.html', context=context)

portfolio/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

portfolio/templates/pages/about.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_javascript %}
  <script type="text/javascript" src="{% static 'js/about.js' %}"></script>
{% endblock %}
{% block title %}Reza Shakeri | {% translate "about" %}{% endblock %}
{% block main_top_bar %}
  {% include 'shared/partials/main_top_bar.html' %}
{% endblock %}
{% block content %}
  <div class="about-section">
    <h1 class="about-title">{{ about.heading }}</h1>
    <div class="about-description">{{ about.body|safe }}</div>
  </div>
{% endblock content %}

portfolio/templates/pages/contact.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_javascript %}
  <script type="text/javascript" src="{% static 'js/contact.js' %}"></script>
{% endblock %}
{% block title %}Reza Shakeri | {% translate "contact us" %}{% endblock %}
{% block social_media %}{% endblock %}
{% block main_top_bar %}
  {% include 'shared/partials/main_top_bar.html' %}
{% endblock %}
{% block content %}
  <div class="contact-us">
    <form class="contact-us-form" method="POST" action="">
      {% csrf_token %}
      <div class="contact-us-form-field first-name-form">
        <label for="first_name">{% translate "first name" %}</label>
        {{ contact_us_form.first_name }}
        {{ contact_us_form.first_name.errors }}
      </div>

      <div class="contact-us-form-field last-name-form">
        <label for="last_name">{% translate "last name" %}</label>
        {{ contact_us_form.last_name }}
        {{ contact_us_form.last_name.errors }}
      </div>

      <div class="contact-us-form-field email-form">
        <label for="email">{% translate "email" %}</label>
        {{ contact_us_form.email }}
        {{ contact_us_form.email.errors }}
      </div>

      <div class="contact-us-form-field message-form">
        <label for="contact-us-message">{% translate "message" %}</label>
        {{ contact_us_form.message }}
        {{ contact_us_form.message.errors }}
      </div>

      <input class="contact-us-button mail-btn" value="Send" type="submit">
    </form>
  </div>
{% endblock content %}

portfolio/templates/pages/index.html
{% extends "base.html" %}
{% load static render_partial %}
{% block extra_javascript %}
  <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}
{% block title %}Reza Shakeri | {{ page.title }}{% endblock %}
{% block social_media %}
  {% render_partial 'pages.views.render_social_media' %}
{% endblock %}
{% block content %}
  <div id="main-menu">
    <div id="main-menu-items">
      <div class="main-menu-head">
        <h1 class="main-menu-head-title">{{ portfolio.name }}</h1>
        <p class="main-menu-head-description">{{ portfolio.job_title }}</p>
      </div>
      <div class="main-menu-item">
        <p class="main-menu-item-text">About Me</p>
        <a class="main-menu-item-link" href="#">Ctrl + A</a>
      </div>
      <div class="main-menu-item">
        <p class="main-menu-item-text">Skills</p>
        <a class="main-menu-item-link" href="#">Ctrl + S</a>
      </div>
      <div class="main-menu-item">
        <p class="main-menu-item-text">Projects</p>
        <a class="main-menu-item-link" href="#">Ctrl + P</a>
      </div>
      <div class="main-menu-item">
        <p class="main-menu-item-text">Home</p>
        <a class="main-menu-item-link" href="#">Ctrl + H</a>
      </div>
    </div>
  </div>
{% endblock content %}

portfolio/templates/pages/project.html
{% extends "base.html" %}
{% load static %}
{% block extra_javascript %}
  <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}
{% block title %}Reza Shakeri | {{ page.title }}{% endblock %}
{% block main_top_bar %}
  {% include 'shared/partials/main_top_bar.html' %}
{% endblock %}
{% block content %}
  <div class="project">
    <div class="project-details">
      <div class="project-head">
        <div class="project-badges">
          <div class="project-badge project-github-star">
            <i class="fa fa-star fa-fade" aria-hidden="true"></i>
            <span>stars: {{ project.star_count }}</span>
          </div>
          <div class="project-badge project-github-fork">
            <i class="fa fa-code-fork" aria-hidden="true"></i>
            <span>fork: {{ project.fork_count }}</span>
          </div>
        </div>
        <h1 class="project-title">{{ project.name }}</h1>
      </div>
      <div class="project-content">
        <div class="project-description">
          {{ project.description|safe }}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

portfolio/templates/pages/projects.html
{% extends "base.html" %}
{% load static i18n %}
{% load static %}
{% block extra_javascript %}
  <script type="text/javascript" src="{% static 'js/projects.js' %}"></script>
{% endblock %}
{% block title %}Reza Shakeri | {% translate "projects" %}{% endblock %}
{% block social_media %}{% endblock %}
{% block main_top_bar %}
  {% include 'shared/partials/main_top_bar.html' %}
{% endblock %}
{% block content %}
  <div class="projects">
    <div class="projects-head">
      <h1 class="projects-head-text">{% translate "Projects" %}</h1>
    </div>
    <div class="projects-content">
      {% for project in projects %}
        <div class="card rounded">
          <div class="card-overlay">
          </div>
          <div class="card-heading">
            <div class="badges">
              <div class="badge github-stars-badge">
                <i class="fa fa-star fa-fade" aria-hidden="true"></i>
                <span>stars: {{ project.star_count }}</span>
              </div>
              <div class="badge github-forks-badge">
                <i class="fa fa-code-fork" aria-hidden="true"></i>
                <span>fork: {{ project.fork_count }}</span>
              </div>
            </div>
            <span class="card-heading-title small"><a class="card-heading-link" href="{% url 'project' slug=project.slug %}">{{ project.name }}</a></span>
            <h2 class="card-heading-description">{{ project.short_description}}</h2>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

portfolio/templates/pages/skills.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_javascript %}
  <script type="text/javascript" src="{% static 'js/skills.js' %}"></script>
{% endblock %}
{% block title %}Reza Shakeri | {% translate "skills" %}{% endblock %}
{% block social_media %}{% endblock %}
{% block main_top_bar %}
  {% include 'shared/partials/main_top_bar.html' %}
{% endblock %}

{% block content %}
  <div class="skills-section">
    <div class="skills-head">
      <h1 class="skills-head-title">{% translate "skills" %}</h1>
    </div>
    <div class="skills-content">
      {% for category in skill_category %}
        <div class="skill-items">
          <p class="skill-title">{{ category.name }}</p>
          <div class="skill-item">
            {% for skill in category.skill_set.all %}
              <div class="skill">
                <img class="skill-icon" src="{{ skill.thumbnail_url }}" alt="">
                <p class="skill-description">{{ skill.name }}</p>
              </div>
            {% endfor %}
          </div>
        </div>
      {% endfor %}

    </div>
  </div>
{% endblock content %}